
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 14 14:09:47 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 28;
  public static final int CHAR = 47;
  public static final int CONST = 7;
  public static final int NOT_EQUAL = 31;
  public static final int SEMI = 41;
  public static final int LPAREN = 26;
  public static final int CONTINUE = 9;
  public static final int MINUS = 49;
  public static final int RPAREN = 40;
  public static final int AND = 2;
  public static final int LT = 27;
  public static final int OR = 35;
  public static final int BOOL = 46;
  public static final int COMMA = 8;
  public static final int CLASS = 6;
  public static final int INC = 22;
  public static final int DOUBLE_DOT = 13;
  public static final int FIND_ANY = 18;
  public static final int DIV = 11;
  public static final int PLUS = 48;
  public static final int ASSIGN = 4;
  public static final int IF = 23;
  public static final int DOT = 12;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int EQUAL = 16;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int PROGRAM = 34;
  public static final int MUL = 29;
  public static final int PERCENT = 32;
  public static final int NUMBER = 45;
  public static final int IDENT = 44;
  public static final int BREAK = 5;
  public static final int VOID = 42;
  public static final int FIND_AND_REPLACE = 17;
  public static final int GTE = 21;
  public static final int LBRACK = 25;
  public static final int ARROW = 3;
  public static final int FOREACH = 19;
  public static final int LBRACE = 24;
  public static final int ELSE = 14;
  public static final int READ = 38;
  public static final int RBRACK = 37;
  public static final int WHILE = 43;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 15;
  public static final int DEC = 10;
  public static final int GT = 20;
  public static final int PRINT = 33;
}

